### ISSUE TITLE
Training CaMN on BEATX 

### ISSUE THREAD

**Issue by fcchit** [PantoMatrix/PantoMatrix#135]
Excellent work!
I want to train CaMN on BEATX using the code provided in EMAGE. It works fine with default training parameters `training_speakers: [2]`, but when changed to `training_speakers: [6]` or other speakers, I get the following error.

```
/opt/conda/conda-bld/pytorch_1695392022560/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [2,0,0], thread: [51,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1695392022560/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [2,0,0], thread: [52,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1695392022560/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [2,0,0], thread: [53,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1695392022560/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [2,0,0], thread: [54,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1695392022560/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [2,0,0], thread: [55,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1695392022560/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [2,0,0], thread: [56,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1695392022560/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [2,0,0], thread: [57,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1695392022560/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [2,0,0], thread: [58,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1695392022560/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [2,0,0], thread: [59,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1695392022560/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [2,0,0], thread: [60,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1695392022560/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [2,0,0], thread: [61,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1695392022560/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [2,0,0], thread: [62,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1695392022560/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [2,0,0], thread: [63,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
 05-07 19:40:58 | An error has been caught in function '<module>', process 'MainProcess' (9384), thread 'MainThread' (140184982701888):
Traceback (most recent call last):

> File "PantoMatrix/scripts/EMAGE_2024/train.py", line 307, in <module>
    main_worker(0, 1, args)
    │                 └ Namespace(config='./scripts/EMAGE_2024/configs/camn.yaml', project='s2g', stat='ts', csv_name='a2g_0', notes='', trainer='cam...
    └ <function main_worker at 0x7f7e64327160>

  File "PantoMatrix/scripts/EMAGE_2024/train.py", line 262, in main_worker
    trainer.val(epoch)
    │       │   └ 0
    │       └ <function CustomTrainer.val at 0x7f7e642ba040>
    └ <camn_trainer.CustomTrainer object at 0x7f7e64328e50>

  File "PantoMatrix/scripts/EMAGE_2024/camn_trainer.py", line 205, in val
    net_out = self._g_training(loaded_data, False, 'val')
              │    │           └ <unprintable dict object>
              │    └ <function CustomTrainer._g_training at 0x7f7e642b9ee0>
              └ <camn_trainer.CustomTrainer object at 0x7f7e64328e50>

  File "PantoMatrix/scripts/EMAGE_2024/camn_trainer.py", line 96, in _g_training
    net_out  = self.model(in_audio = loaded_data['in_audio'], pre_seq = loaded_data["in_motion"], in_text=loaded_data["tar_word"], in_id=loaded_data["tar_id"], in_emo=loaded_data["in_emo"], in_facial = loaded_data["tar_exps"])
               │    │                │                                  │                                 │                              │                             │                                  └ <unprintable dict object>
               │    │                │                                  │                                 │                              │                             └ <unprintable dict object>
               │    │                │                                  │                                 │                              └ <unprintable dict object>
               │    │                │                                  │                                 └ <unprintable dict object>
               │    │                │                                  └ <unprintable dict object>
               │    │                └ <unprintable dict object>
               │    └ DataParallel(
               │        (module): CaMN(
               │          (audio_encoder): WavEncoder(
               │            (feat_extractor): Sequential(
               │              (0): BasicBlock(...
               └ <camn_trainer.CustomTrainer object at 0x7f7e64328e50>

  File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           │    │           │       └ <unprintable dict object>
           │    │           └ ()
           │    └ <function Module._call_impl at 0x7f7e9989bc10>
           └ DataParallel(
               (module): CaMN(
                 (audio_encoder): WavEncoder(
                   (feat_extractor): Sequential(
                     (0): BasicBlock(...
  File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           │             │       └ <unprintable dict object>
           │             └ ()
           └ <bound method DataParallel.forward of DataParallel(
               (module): CaMN(
                 (audio_encoder): WavEncoder(
                   (feat_extractor)...
  File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 183, in forward
    return self.module(*inputs[0], **module_kwargs[0])
           │            │            └ <unprintable tuple object>
           │            └ ((),)
           └ DataParallel(
               (module): CaMN(
                 (audio_encoder): WavEncoder(
                   (feat_extractor): Sequential(
                     (0): BasicBlock(...
  File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           │    │           │       └ <unprintable dict object>
           │    │           └ ()
           │    └ <function Module._call_impl at 0x7f7e9989bc10>
           └ CaMN(
               (audio_encoder): WavEncoder(
                 (feat_extractor): Sequential(
                   (0): BasicBlock(
                     (conv1): Conv1d(1, 32, ...
  File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           │             │       └ <unprintable dict object>
           │             └ ()
           └ <bound method CaMN.forward of CaMN(
               (audio_encoder): WavEncoder(
                 (feat_extractor): Sequential(
                   (0): BasicBlock(
              ...

  File "PantoMatrix/scripts/EMAGE_2024/models/camn.py", line 376, in forward
    text_feat_seq, _ = self.text_encoder(in_text)
    │                  │                 └ <unprintable Tensor object>
    │                  └ CaMN(
    │                      (audio_encoder): WavEncoder(
    │                        (feat_extractor): Sequential(
    │                          (0): BasicBlock(
    │                            (conv1): Conv1d(1, 32, ...
    └ None

  File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           │    │           │       └ {}
           │    │           └ <unprintable tuple object>
           │    └ <function Module._call_impl at 0x7f7e9989bc10>
           └ TextEncoderTCN(
               (embedding): Embedding(11195, 300)
               (tcn): TemporalConvNet(
                 (network): Sequential(
                   (0): Temporal...
  File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           │             │       └ {}
           │             └ <unprintable tuple object>
           └ <bound method TextEncoderTCN.forward of TextEncoderTCN(
               (embedding): Embedding(11195, 300)
               (tcn): TemporalConvNet(
                 (n...

  File "PantoMatrix/scripts/EMAGE_2024/models/camn.py", line 117, in forward
    y = self.tcn(emb.transpose(1, 2)).transpose(1, 2)
        │        │   └ <method 'transpose' of 'torch._C._TensorBase' objects>
        │        └ <unprintable Tensor object>
        └ TextEncoderTCN(
            (embedding): Embedding(11195, 300)
            (tcn): TemporalConvNet(
              (network): Sequential(
                (0): Temporal...

  File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           │    │           │       └ {}
           │    │           └ <unprintable tuple object>
           │    └ <function Module._call_impl at 0x7f7e9989bc10>
           └ TemporalConvNet(
               (network): Sequential(
                 (0): TemporalBlock(
                   (conv1): Conv1d(300, 512, kernel_size=(2,), stride=(1...
  File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           │             │       └ {}
           │             └ <unprintable tuple object>
           └ <bound method TemporalConvNet.forward of TemporalConvNet(
               (network): Sequential(
                 (0): TemporalBlock(
                   (conv1): Con...

  File "PantoMatrix/scripts/EMAGE_2024/models/camn.py", line 77, in forward
    return self.network(x)
           │            └ <unprintable Tensor object>
           └ TemporalConvNet(
               (network): Sequential(
                 (0): TemporalBlock(
                   (conv1): Conv1d(300, 512, kernel_size=(2,), stride=(1...

  File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           │    │           │       └ {}
           │    │           └ <unprintable tuple object>
           │    └ <function Module._call_impl at 0x7f7e9989bc10>
           └ Sequential(
               (0): TemporalBlock(
                 (conv1): Conv1d(300, 512, kernel_size=(2,), stride=(1,), padding=(1,))
                 (chomp1): Ch...
  File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           │             │       └ {}
           │             └ <unprintable tuple object>
           └ <bound method Sequential.forward of Sequential(
               (0): TemporalBlock(
                 (conv1): Conv1d(300, 512, kernel_size=(2,), stride=...
  File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/container.py", line 215, in forward
    input = module(input)
            │      └ <unprintable Tensor object>
            └ TemporalBlock(
                (conv1): Conv1d(300, 512, kernel_size=(2,), stride=(1,), padding=(1,))
                (chomp1): Chomp1d()
                (relu1): ReLU...
  File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           │    │           │       └ {}
           │    │           └ <unprintable tuple object>
           │    └ <function Module._call_impl at 0x7f7e9989bc10>
           └ TemporalBlock(
               (conv1): Conv1d(300, 512, kernel_size=(2,), stride=(1,), padding=(1,))
               (chomp1): Chomp1d()
               (relu1): ReLU...
  File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           │             │       └ {}
           │             └ <unprintable tuple object>
           └ <bound method TemporalBlock.forward of TemporalBlock(
               (conv1): Conv1d(300, 512, kernel_size=(2,), stride=(1,), padding=(1,)...

  File "PantoMatrix/scripts/EMAGE_2024/models/camn.py", line 51, in forward
    out = self.net(x)
          │        └ <unprintable Tensor object>
          └ TemporalBlock(
              (conv1): Conv1d(300, 512, kernel_size=(2,), stride=(1,), padding=(1,))
              (chomp1): Chomp1d()
              (relu1): ReLU...

  File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           │    │           │       └ {}
           │    │           └ <unprintable tuple object>
           │    └ <function Module._call_impl at 0x7f7e9989bc10>
           └ Sequential(
               (0): Conv1d(300, 512, kernel_size=(2,), stride=(1,), padding=(1,))
               (1): Chomp1d()
               (2): ReLU()
               (3): Dropou...
  File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           │             │       └ {}
           │             └ <unprintable tuple object>
           └ <bound method Sequential.forward of Sequential(
               (0): Conv1d(300, 512, kernel_size=(2,), stride=(1,), padding=(1,))
               (1): C...
  File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/container.py", line 215, in forward
    input = module(input)
            │      └ <unprintable Tensor object>
            └ Conv1d(300, 512, kernel_size=(2,), stride=(1,), padding=(1,))
  File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           │    │           │       └ {}
           │    │           └ <unprintable tuple object>
           │    └ <function Module._call_impl at 0x7f7e9989bc10>
           └ Conv1d(300, 512, kernel_size=(2,), stride=(1,), padding=(1,))
  File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
             │             │       └ {}
             │             └ <unprintable tuple object>
             └ <bound method Conv1d.forward of Conv1d(300, 512, kernel_size=(2,), stride=(1,), padding=(1,))>
  File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 310, in forward
    return self._conv_forward(input, self.weight, self.bias)
           │    │             │      │    │       └ Conv1d(300, 512, kernel_size=(2,), stride=(1,), padding=(1,))
           │    │             │      │    └ <unprintable Tensor object>
           │    │             │      └ Conv1d(300, 512, kernel_size=(2,), stride=(1,), padding=(1,))
           │    │             └ <unprintable Tensor object>
           │    └ <function Conv1d._conv_forward at 0x7f7e995e5550>
           └ Conv1d(300, 512, kernel_size=(2,), stride=(1,), padding=(1,))
  File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 306, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
           │ │      │      │       │     │    └ (1,)
           │ │      │      │       │     └ Conv1d(300, 512, kernel_size=(2,), stride=(1,), padding=(1,))
           │ │      │      │       └ <unprintable Parameter object>
           │ │      │      └ <unprintable Tensor object>
           │ │      └ <unprintable Tensor object>
           │ └ <built-in method conv1d of type object at 0x7f7f0ca46a40>
           └ <module 'torch.nn.functional' from '/root/miniconda3/lib/python3.9/site-packages/torch/nn/functional.py'>

RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

I'm using torch 2.1.0 with cuda 11.8 and tried torch 2.0.1 with cuda 11.7 and torch 2.2.0 with cuda 11.8. But the same error happened.

I use the following command to train CaMN.

```shell
python scripts/EMAGE_2024/train.py --config ./scripts/EMAGE_2024/configs/camn.yaml 
```

Do you have any suggestions on this issue? Many thanks for you attention.

**Comment by fcchit** [comment]
I've solved the problem. I wanted to use 25 speakers for training, but the `speaker_dims` in `utils/config.py' is **4**, that's why the error occurs.
